# Generated by Django 6.0.7 on 2026-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beautician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, help_text="Static fallback path, e.g. 'images/hero-bg.jpg' — only used if neither field below is set.", max_length=200)),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.CharField(help_text="Free text, e.g. '9 yrs experience'", max_length=60)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('skills', models.JSONField(default=list, help_text='List of short skill strings')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BeautyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, help_text="Static fallback path, e.g. 'images/hero-bg.jpg' — only used if neither field below is set.", max_length=200)),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('excerpt', models.TextField()),
                ('read_time', models.CharField(help_text="Free text, e.g. '4 min read'", max_length=30)),
                ('date', models.DateField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Beauty tip',
                'ordering': ['sort_order', '-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('tone', models.CharField(blank=True, help_text='CSS tone modifier, e.g. espresso/blush/gold', max_length=20)),
                ('before_photo', models.CharField(blank=True, help_text='Static fallback path', max_length=200)),
                ('before_photo_image', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('before_photo_url', models.URLField(blank=True, max_length=500)),
                ('after_photo', models.CharField(blank=True, help_text='Static fallback path', max_length=200)),
                ('after_photo_image', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('after_photo_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery before/after',
                'verbose_name_plural': 'Gallery before/afters',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, help_text="Static fallback path, e.g. 'images/hero-bg.jpg' — only used if neither field below is set.", max_length=200)),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('label', models.CharField(max_length=100)),
                ('tone', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery portfolio item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('headline_lines', models.JSONField(default=list, help_text='List of headline lines, e.g. ["Premium Salon", "at Home."]')),
                ('subhead', models.TextField(blank=True)),
                ('primary_cta_label', models.CharField(blank=True, max_length=60)),
                ('primary_cta_href', models.CharField(blank=True, max_length=200)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=60)),
                ('secondary_cta_href', models.CharField(blank=True, max_length=200)),
                ('stats', models.JSONField(default=list, help_text='List of {value, suffix, label}')),
                ('floating_chips', models.JSONField(blank=True, default=list, help_text='List of short strings')),
                ('photo', models.CharField(blank=True, max_length=200)),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(help_text="Display label, e.g. '01'", max_length=4)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'How It Works step',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('time_label', models.CharField(help_text="Free text, e.g. '2h ago'", max_length=30)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('read', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('quote', models.TextField()),
                ('service', models.CharField(help_text='The service name this customer is quoted about', max_length=140)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrendingSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrustPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=10)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValuePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(help_text="Display label, e.g. '01'", max_length=4)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('image', models.CharField(help_text='Key used as images/pillar-<image>.jpg', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
