# Generated by Django 6.0.7 on 2026-08-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_site_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beautician',
        ),
    ]
