# Generated by Django 6.0.7 on 2026-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_beautician'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, help_text="Static fallback path, e.g. 'images/hero-bg.jpg' — only used if neither field below is set.", max_length=200)),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to='site/%Y/%m/')),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=140)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_href', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
