"""
Django settings for GlamourAtHome project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^sroozd3j&^fm6s5m!%ro@q#f92q2sffk+lmdchs-65h21t&(5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GlamourAtHome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Injects brand/site-wide data (name, contact, socials, app links)
                # into every template so navbar/footer never hardcode it.
                'core.context_processors.site_meta',
            ],
        },
    },
]

WSGI_APPLICATION = 'GlamourAtHome.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target for production

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Site-wide constants (consumed by core.context_processors.site_meta).
# Centralised here so brand/contact details are edited in exactly one place.
# ---------------------------------------------------------------------------
SITE_NAME = 'Glamour At Home'
SITE_TAGLINE = 'Luxury beauty, at your doorstep.'
SITE_DOMAIN = 'glamourathome.com'  # update for the real production domain
SITE_DESCRIPTION = (
    'Glamour At Home brings verified, professional beauticians and premium '
    'products to your doorstep — salon-grade hair, skin, makeup and spa '
    'services on your schedule, in your space.'
)
SITE_PHONE = '+91 90000 00000'
SITE_EMAIL = 'hello@glamourathome.com'
SITE_ADDRESS = 'Bengaluru, Karnataka, India'
SOCIAL_LINKS = {
    'instagram': 'https://instagram.com/glamourathome',
    'facebook': 'https://facebook.com/glamourathome',
    'youtube': 'https://youtube.com/@glamourathome',
    'linkedin': 'https://linkedin.com/company/glamourathome',
}
APP_LINKS = {
    'android': 'https://play.google.com/store/apps/details?id=com.glamourathome.app',
    'ios': 'https://apps.apple.com/app/glamour-at-home/id0000000000',
}
