"""
Django settings for GlamourAtHome project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Was hardcoded in source (committed to git) — moved to .env, same pattern
# as every other credential in this file. The literal below is ONLY the
# default used when .env doesn't set one, so local dev keeps working with
# zero setup; a real deploy MUST set SECRET_KEY in its own environment.
SECRET_KEY = config('SECRET_KEY', default='django-insecure-^sroozd3j&^fm6s5m!%ro@q#f92q2sffk+lmdchs-65h21t&(5')

# SECURITY WARNING: don't run with debug turned on in production!
# Default stays True so nothing changes for local dev unless .env
# explicitly sets DEBUG=False — see .env.example.
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*,0.0.0.0,localhost,0.0.0.0:8005', cast=Csv())

# Needed to test this over a devtunnels/ngrok-style HTTPS tunnel (the tunnel
# terminates TLS and forwards plain HTTP to this dev server) — without
# these two, Django thinks every request is insecure over plain HTTP:
# - CSRF_TRUSTED_ORIGINS: otherwise every POST (login/signup forms, not
#   just OAuth) fails CSRF verification, since Django checks the request's
#   Origin header against this list for any "unsafe" request.
# - SECURE_PROXY_SSL_HEADER: otherwise request.build_absolute_uri() (which
#   allauth uses to build the Google/Apple OAuth callback URL) reports
#   http:// instead of https://, mismatching whatever https:// redirect URI
#   is registered in Google Cloud Console.
# While devtunnels port-forwarding is active on 8003/8004, it tags *all*
# traffic through that port as forwarded-https — even a direct
# http://localhost:8003 or http://127.0.0.1:8004 hit, not just genuine
# tunnel traffic — since the forwarder can't tell them apart. That makes
# Django expect an https:// origin for a request whose real Origin header
# says http://, so both schemes are listed here for each local dev host/port.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8003', 'https://localhost:8003',
    'http://localhost:8004', 'https://localhost:8004',
    'http://127.0.0.1:8003', 'https://127.0.0.1:8003',
    'http://127.0.0.1:8004', 'https://127.0.0.1:8004',
]
if DEBUG:
    # devtunnels mints a random subdomain per session — a real wildcard
    # trust like this is only appropriate for a throwaway dev tunnel, not
    # a real deployment (anyone with *any* devtunnels subdomain could
    # satisfy this Origin check), so it's gated on DEBUG rather than
    # listed unconditionally above with the fixed local ports.
    CSRF_TRUSTED_ORIGINS.append('https://*.devtunnels.ms')

extra_origins = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
for origin in extra_origins:
    origin = origin.strip()
    if origin:
        if not (origin.startswith('http://') or origin.startswith('https://')):
            CSRF_TRUSTED_ORIGINS.append(f'https://{origin}')
            CSRF_TRUSTED_ORIGINS.append(f'http://{origin}')
        else:
            CSRF_TRUSTED_ORIGINS.append(origin)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# CORS (django-cors-headers) — only matters for the Flutter app's web
# build (`flutter run -d chrome`, or a future web deploy); native
# iOS/Android requests are never subject to CORS, only browsers enforce
# it. No credentials/cookies involved (the mobile API uses a bearer
# token — see api/auth.py), so CORS_ALLOW_CREDENTIALS is deliberately
# left off. Regex, not a fixed port, because `flutter run -d chrome`
# picks a random port each run unless --web-port is passed — same
# "trust any local dev port" reasoning as the devtunnels wildcard
# above, scoped to DEBUG the same way.
CORS_ALLOWED_ORIGIN_REGEXES = []
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://localhost:\d+$',
        r'^http://127\.0\.0\.1:\d+$',
    ]

# Cookie/transport hardening — gated on `not DEBUG` so local dev (plain
# HTTP on localhost) is completely unaffected; only takes effect once a
# real deploy sets DEBUG=False, at which point the site should only ever
# be served over HTTPS anyway.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True

CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Deliberately NOT 'cloudinary_storage' — that app's only effect on
    # INSTALLED_APPS is registering a `collectstatic` command override
    # (checking the pre-Django-4.2 `STATICFILES_STORAGE` setting, which
    # no longer exists once STORAGES below is used — crashes collectstatic
    # outright otherwise: AttributeError, found running `deploy.sh` for
    # real). `MediaCloudinaryStorage` (used below) is a plain importable
    # class — it needs no AppConfig/app registration to work as a STORAGES
    # backend, since static files were never routed to Cloudinary anyway.
    'cloudinary',
    'anymail',
    'corsheaders',

    # django-allauth — see "Authentication" in developed.md. django.contrib.sites
    # is a hard requirement of allauth (it associates SocialApps with a Site).
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',

    # Local apps
    'core',
    'accounts',
    'catalog',
    'bookings',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must sit above CommonMiddleware — corsheaders' own docs require
    # this ordering to actually attach CORS headers to the response.
    # Only relevant to the Flutter app's web build (flutter run -d
    # chrome / a web deploy) — native iOS/Android http calls are never
    # subject to CORS, browsers are the only thing enforcing it.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # Must come after AuthenticationMiddleware (needs request.user) and
    # AccountMiddleware (allauth's own login-stage/flow redirects take
    # priority — this only concerns itself with role-based routing once
    # a user is fully authenticated). See core/middleware.py.
    'core.middleware.RoleRedirectMiddleware',
]

ROOT_URLCONF = 'GlamourAtHome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Injects brand/site-wide data (name, contact, socials, app links)
                # into every template so navbar/footer never hardcode it.
                'core.context_processors.site_meta',
                'core.context_processors.user_roles',
                'core.context_processors.admin_sidebar_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'GlamourAtHome.wsgi.application'

# django.contrib.sites — required by allauth.
SITE_ID = 1

# Django's default ModelBackend still needed for the Django admin;
# allauth's backend adds email-based login on top of it.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Postgres when server DB creds are present in .env (DB_HOST is the
# signal — a plain local checkout with no creds falls back to SQLite
# automatically), SQLite otherwise. Locally that means: as soon as this
# .env has real Postgres creds, `runserver` talks to that Postgres
# instance directly — there's no separate "local mode" override once
# the creds exist, so don't drop real Postgres creds into a local .env
# unless you actually want this machine writing to that database.
DB_HOST = config('DB_HOST', default='')
if DB_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'HOST': DB_HOST,
            'PORT': config('DB_PORT', default='5432'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target for production

# User-uploaded files (employee face-verification photos, job-site arrival
# photos, catalog/marketing-content images — see accounts.Employee /
# bookings.Booking / catalog.* / core.models). Routed to Cloudinary
# (added 2026-08-11) rather than local disk — MEDIA_ROOT below is kept
# only as the fallback local path Django's FileField API still wants
# defined, not actually where uploads land once CLOUDINARY_STORAGE is
# configured.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}
STORAGES = {
    'default': {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'},
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Site-wide constants (consumed by core.context_processors.site_meta).
# Centralised here so brand/contact details are edited in exactly one place.
# ---------------------------------------------------------------------------
SITE_NAME = 'Elix'
SITE_TAGLINE = 'Premium Salon at Home'
SITE_DOMAIN = config('SITE_DOMAIN', default='elix.com')
SITE_DESCRIPTION = (
    'Elix brings verified, professional beauticians and premium products '
    'to your doorstep — salon-grade hair, skin, makeup and spa services on '
    'your schedule, in your space.'
)
SITE_PHONE = '+91 90000 00000'
SITE_EMAIL = 'hello@elix.com'
SITE_ADDRESS = 'Indore, Madhya Pradesh, India'
SOCIAL_LINKS = {
    'instagram': 'https://instagram.com/elix',
    'facebook': 'https://facebook.com/elix',
    'youtube': 'https://youtube.com/@elix',
    'linkedin': 'https://linkedin.com/company/elix',
}
APP_LINKS = {
    'android': 'https://play.google.com/store/apps/details?id=com.elix.app',
    'ios': 'https://apps.apple.com/app/elix/id0000000000',
}

# ---------------------------------------------------------------------------
# Service Booking app (/booking/) — Phase 2 integration keys.
# Read from .env (gitignored; see .env.example), default to '' so Phase 1
# (catalog/cart) runs with zero setup. Not consumed by any view yet — Phase 2
# (booking drawer: Google Maps address step, Razorpay payment step) is what
# will read these. See developed.md "Service Booking App" section.
# ---------------------------------------------------------------------------
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')
# Off by default even with a real key set above — a key alone doesn't mean
# Google Maps Platform actually works: it also requires billing enabled on
# the Google Cloud project (a card on file), or every call (map render,
# Geocoder) fails with REQUEST_DENIED ("This page can't load Google Maps
# correctly"). Flip to True in .env once billing is confirmed enabled; the
# free/keyless Leaflet + OpenStreetMap + Nominatim implementation (see
# booking_drawer.js) stays in the codebase either way, never deleted, so
# switching back is just flipping this flag again.
USE_GOOGLE_MAPS_FOR_ADDRESS = config('USE_GOOGLE_MAPS_FOR_ADDRESS', default=False, cast=bool)
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')

# ---------------------------------------------------------------------------
# Authentication (django-allauth) — see developed.md "Authentication".
# Three-tier login/signup: Google/Apple first, phone OTP second,
# username-or-email + password third. Google/Apple credentials below
# follow the exact same "reserved .env slot, default empty, wire up
# later" pattern as GOOGLE_MAPS_API_KEY/RAZORPAY_KEY_ID above — the
# buttons render now, actual sign-in only works once real values are
# dropped into .env.
# ---------------------------------------------------------------------------
ACCOUNT_ADAPTER = 'accounts.adapter.AccountAdapter'
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
    'reset_password': 'accounts.forms.CustomResetPasswordForm',
}
SOCIALACCOUNT_FORMS = {'signup': 'accounts.forms.CustomSocialSignupForm'}

ACCOUNT_LOGIN_METHODS = {'username', 'email', 'phone'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'phone*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
# Tier-2 login ("Continue with Phone Number") no longer uses allauth's own
# login-by-code — MessageCentral's Verify Now product generates and
# validates its own OTP (accounts/phone_login_views.py +
# accounts/messagecentral.py), so allauth's parallel implementation of
# the same idea is switched off to avoid two competing phone-OTP paths.
ACCOUNT_LOGIN_BY_CODE_ENABLED = False
# Would insert a MANDATORY "verify your phone" stage on every single
# login (any method — password, Google, even phone-code) for any account
# whose phone isn't marked verified, which isn't what "three alternative
# ways to log in" meant. Phone still gets marked verified automatically
# the moment someone actually completes the MessageCentral phone-login
# flow once (see accounts/phone_login_views.py).
ACCOUNT_PHONE_VERIFICATION_ENABLED = False
# Was `False` ("dev-friendly") — that leaves login, phone-OTP request/
# confirm, and password reset completely unthrottled, which is what
# actually makes credential-stuffing/OTP-brute-force practical rather
# than just theoretical. There is no boolean "on" for this setting
# though — allauth's app_settings.RATE_LIMITS property does
# `ret.update(rls)` on whatever this is, and `dict.update(True)` raises
# TypeError, taking down every allauth view that checks a rate limit
# (login, signup, password reset...). Leaving this as a dict (even
# empty) makes allauth fall back to its own sane built-in per-action
# defaults for its own views; the two keys below are OUR custom
# actions (accounts/phone_login_views.py's MessageCentral-backed tier-2
# login, which isn't an allauth view at all) — added here because
# allauth.core.ratelimit.consume() reads rates from this exact same
# merged dict for ANY action name, not just its own.
ACCOUNT_RATE_LIMITS = {
    'phone_login_request': '20/m/ip,3/m/key',
    'phone_login_resend': '5/m/key',
}
ACCOUNT_LOGOUT_ON_GET = True  # Immediately log out on clicking Logout without confirmation page

# MessageCentral "Verify Now" (phone-OTP send + validate) — see
# accounts/messagecentral.py. The customerId is decoded out of this key
# itself (it's a JWT carrying it), so no second .env value is needed for
# that. MESSAGECENTRAL_PASSWORD is a separate credential though — per
# their own onboarding guide, send/validate need a session token from
# /auth/v1/authentication/token first, and THAT call needs the actual
# dashboard login password (base64-encoded), not this "Auth Token".
MESSAGECENTRAL_AUTH_TOKEN = config('SMS_KEY', default='')
# False -> accounts/messagecentral.py prints the OTP to the console
# instead of calling the real gateway (no real send/receive round trip,
# no credits spent) — same "console fallback for dev" pattern as
# EMAIL_BACKEND above. True -> real MessageCentral send/validate calls.
OTP_GATEWAY = config('OTP_GATEWAY', default=False, cast=bool)
MESSAGECENTRAL_PASSWORD = config('MESSAGECENTRAL_PASSWORD', default='')

LOGIN_REDIRECT_URL = '/booking/'
LOGOUT_REDIRECT_URL = '/booking/'
LOGIN_URL = '/accounts/login/'

# Skip allauth's own "You are about to sign in via Google/Apple — Continue"
# confirmation page — go straight to the provider instead. Safe here since
# our own login/signup templates already ask for explicit confirmation (the
# user clicks "Continue with Google/Apple" themselves); allauth's extra
# click was a redundant second confirmation, not a security boundary.
SOCIALACCOUNT_LOGIN_ON_GET = True

# Real transactional email via Brevo (through Anymail's Brevo backend) —
# added 2026-08-11, replacing the console backend that just printed emails
# (password reset, optional verification) to the runserver log. Falls back
# to the console backend if no API key is configured (e.g. a local
# checkout with no .env secrets), so email sending never hard-fails setup.
if config('BREVO_API_KEY', default=''):
    EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
    ANYMAIL = {'BREVO_API_KEY': config('BREVO_API_KEY')}
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=SITE_EMAIL)

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_OAUTH_CLIENT_ID', default=''),
            'secret': config('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        # Without this, Google silently reuses whichever Google account is
        # already logged into the browser and never shows the account
        # chooser — logging out of this site does nothing to change that,
        # since it's Google's own session cookie, not ours. Forces the
        # picker every time so switching accounts actually works.
        'AUTH_PARAMS': {'prompt': 'select_account'},
    },
    'apple': {
        'APP': {
            'client_id': config('APPLE_OAUTH_CLIENT_ID', default=''),  # Services ID
            'secret': config('APPLE_OAUTH_TEAM_ID', default=''),       # Team ID
            'key': config('APPLE_OAUTH_KEY_ID', default=''),           # Key ID
            'settings': {
                # Contents of the .p8 private key file downloaded once from
                # Apple — used to sign the JWT client-secret allauth generates
                # per request. 'certificate_key' at the top level of APP also
                # works but is deprecated in favor of nesting it here.
                'certificate_key': config('APPLE_OAUTH_PRIVATE_KEY', default=''),
            },
        },
    },
}
