# Generated by Django 6.0.7 on 2026-08-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialties', models.CharField(help_text='e.g. Hair Spa, Facials, Makeup', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=15)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('photo', models.CharField(blank=True, help_text='Static photo path', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
