# Generated by Django 6.0.7 on 2026-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_photo_bottom',
            field=models.ImageField(blank=True, help_text='Chin up, eyes looking down toward the camera', null=True, upload_to='employee_faces/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_photo_front',
            field=models.ImageField(blank=True, help_text='Straight-on, looking directly at the camera', null=True, upload_to='employee_faces/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_photo_left',
            field=models.ImageField(blank=True, help_text='Head turned to show your left profile', null=True, upload_to='employee_faces/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_photo_right',
            field=models.ImageField(blank=True, help_text='Head turned to show your right profile', null=True, upload_to='employee_faces/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='face_photo_top',
            field=models.ImageField(blank=True, help_text='Chin down, eyes looking up toward the camera', null=True, upload_to='employee_faces/%Y/%m/'),
        ),
    ]
