# Generated by Django 6.0.7 on 2026-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_create_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='employees/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='reviews',
            field=models.PositiveIntegerField(default=0, help_text='Shown on the public "meet the team" card'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of short skill strings, e.g. ["Threading", "Honey Wax"] — shown on the public card'),
        ),
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordering on the public "meet the team" carousel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.CharField(blank=True, help_text='Static fallback photo path — only used if neither field below is set.', max_length=200),
        ),
    ]
