# Generated by Django 6.0.7 on 2026-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_employee_face_photo_bottom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleave',
            options={'ordering': ['start_date', 'start_time']},
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for short breaks (optional)', null=True),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(choices=[('full_day', 'Full Day Leave'), ('short_break', 'Short Break / Time Slot'), ('multi_day', 'Multi-Day Leave')], default='full_day', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time for short breaks (optional)', null=True),
        ),
    ]
