# Generated by Django 6.0.7 on 2026-08-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_employeeleave_options_employeeleave_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_embedding',
            field=models.JSONField(blank=True, help_text='Pre-calculated 128-d ML face embedding vector for 1:1 facial verification', null=True),
        ),
    ]
