# Generated by Django 6.0.7 on 2026-10-05 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


import re


def backfill_employee_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Employee = apps.get_model('accounts', 'Employee')
    Profile = apps.get_model('accounts', 'Profile')

    emp_group, _ = Group.objects.get_or_create(name='emp')

    for emp in Employee.objects.all():
        if not emp.user_id:
            raw_name = getattr(emp, 'name', '') or 'Staff'
            parts = raw_name.split(None, 1)
            first = parts[0]
            last = parts[1] if len(parts) > 1 else ''
            base_uname = re.sub(r'[^a-z0-9]', '', (first + last).lower()) or 'emp'
            uname = base_uname
            c = 1
            while User.objects.filter(username=uname).exists():
                c += 1
                uname = f"{base_uname}{c}"
            user = User.objects.create(
                username=uname,
                first_name=first,
                last_name=last,
                email=getattr(emp, 'email', '') or '',
                is_active=True,
            )
            user.set_password(User.objects.make_random_password())
            user.save()
            user.groups.add(emp_group)
            emp.user = user
            emp.save(update_fields=['user'])
        else:
            user = emp.user
            raw_name = getattr(emp, 'name', '') or ''
            if raw_name and not user.first_name and not user.last_name:
                parts = raw_name.split(None, 1)
                user.first_name = parts[0]
                user.last_name = parts[1] if len(parts) > 1 else ''
                user.save(update_fields=['first_name', 'last_name'])
            raw_email = getattr(emp, 'email', '') or ''
            if raw_email and not user.email:
                user.email = raw_email
                user.save(update_fields=['email'])

        raw_phone = getattr(emp, 'phone', '') or ''
        if raw_phone and emp.user:
            Profile.objects.update_or_create(user=emp.user, defaults={'phone': raw_phone})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_employee_face_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_employee_users, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
