#!/usr/bin/env bash
# Deploy/redeploy Elix on the Oracle VM — safe to re-run (pulls latest,
# reinstalls deps, migrates, restarts). Demo deployment, not a hardened
# production setup: single gunicorn instance behind nginx, systemd for
# process supervision, certbot for HTTPS. This VM also runs other,
# unrelated projects — every path/service/socket name here is scoped to
# "elix" specifically so this script never touches them.
#
# Usage (on the Oracle VM, as a user with sudo):
#   sudo REPO_URL=git@github.com:vindhyatech-in/Elix-Premium.git \
#        CERTBOT_EMAIL=you@example.com \
#        ./deploy.sh
#
# First run: clones the repo, sets up the venv, installs nginx/certbot,
# and asks you to fill in /var/www/elix/.env before it can finish
# (real secrets are never generated by this script, and never committed
# to git — see .env.example).
set -euo pipefail

DOMAIN="elix.vindhyatech.in"
PROJECT_DIR="/var/www/elix"
REPO_URL="${REPO_URL:-https://github.com/vindhyatech-in/Elix-Premium.git}"
BRANCH="${BRANCH:-main}"
SERVICE_NAME="elix"
RUN_USER="www-data"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this with sudo — it installs system packages and writes to /etc/." >&2
  exit 1
fi

echo "==> Installing system packages (skips anything already present)"
apt-get update -qq
apt-get install -y -qq python3 python3-venv python3-pip nginx certbot python3-certbot-nginx git > /dev/null

echo "==> Fetching code"
if [ -d "$PROJECT_DIR/.git" ]; then
  git -C "$PROJECT_DIR" fetch origin "$BRANCH"
  git -C "$PROJECT_DIR" checkout "$BRANCH"
  git -C "$PROJECT_DIR" reset --hard "origin/$BRANCH"
else
  mkdir -p "$(dirname "$PROJECT_DIR")"
  git clone --branch "$BRANCH" "$REPO_URL" "$PROJECT_DIR"
fi

echo "==> Python virtualenv + dependencies"
if [ ! -f "$PROJECT_DIR/venv/bin/pip" ]; then
  rm -rf "$PROJECT_DIR/venv"
  python3 -m venv "$PROJECT_DIR/venv"
fi
"$PROJECT_DIR/venv/bin/pip" install -q --upgrade pip
"$PROJECT_DIR/venv/bin/pip" install -q -r "$PROJECT_DIR/requirements.txt"

if [ ! -f "$PROJECT_DIR/.env" ]; then
  cp "$PROJECT_DIR/.env.example" "$PROJECT_DIR/.env"
  echo
  echo "!! $PROJECT_DIR/.env created from .env.example but is still blank."
  echo "!! Fill in real values (SECRET_KEY, DEBUG=False, ALLOWED_HOSTS=$DOMAIN,"
  echo "!! CSRF_TRUSTED_ORIGINS=https://$DOMAIN, DB_*, CLOUDINARY_*, etc.),"
  echo "!! then re-run this script."
  exit 1
fi

if grep -q "^DEBUG=True" "$PROJECT_DIR/.env"; then
  echo "!! $PROJECT_DIR/.env still has DEBUG=True — set DEBUG=False before" >&2
  echo "!! deploying a real domain (stack traces would otherwise be public)." >&2
  exit 1
fi

echo "==> Django migrate + collectstatic"
cd "$PROJECT_DIR"
"$PROJECT_DIR/venv/bin/python" manage.py migrate --noinput
"$PROJECT_DIR/venv/bin/python" manage.py collectstatic --noinput > /dev/null

echo "==> File ownership"
chown -R "$RUN_USER:$RUN_USER" "$PROJECT_DIR"

echo "==> systemd service"
cp "$PROJECT_DIR/deploy/elix.service" "/etc/systemd/system/$SERVICE_NAME.service"
systemctl daemon-reload
systemctl enable "$SERVICE_NAME" > /dev/null
systemctl restart "$SERVICE_NAME"

echo "==> nginx site"
cp "$PROJECT_DIR/deploy/nginx_elix.conf" "/etc/nginx/sites-available/$DOMAIN"
ln -sf "/etc/nginx/sites-available/$DOMAIN" "/etc/nginx/sites-enabled/$DOMAIN"
nginx -t
systemctl reload nginx

echo "==> HTTPS (certbot) — no-ops if already valid"
if [ -n "$CERTBOT_EMAIL" ]; then
  certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$CERTBOT_EMAIL" --redirect
else
  echo "!! CERTBOT_EMAIL not set — skipping HTTPS setup. Re-run with"
  echo "!! CERTBOT_EMAIL=you@example.com to enable it, or run manually:"
  echo "!!   certbot --nginx -d $DOMAIN --redirect"
fi

echo "==> Smoke test"
sleep 1
curl -fsS -o /dev/null -w "  HTTP status: %{http_code}\n" "http://$DOMAIN/" || echo "  (request failed — check 'systemctl status $SERVICE_NAME' and 'journalctl -u $SERVICE_NAME')"

echo
echo "Done. Service: systemctl status $SERVICE_NAME | journalctl -u $SERVICE_NAME -f"
