# Generated by Django 6.0.7 on 2026-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_replace_demo_with_real_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='included_services',
            field=models.ManyToManyField(blank=True, help_text='Select single services included in this package', related_name='included_in_packages', to='catalog.service'),
        ),
    ]
