# Generated by Django 6.0.7 on 2026-08-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_description_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='service',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.CharField(blank=True, help_text="Static path, e.g. 'images/service-hair-spa.jpg' — only used if neither photo below is set.", max_length=200),
        ),
    ]
