# Generated by Django 6.0.7 on 2026-09-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_category_image_alter_package_photo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first. Edit this to reorder steps.')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, help_text="Short label shown on the step chip, e.g. 'KEY STEP', '5 mins'.", max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_steps/%Y/%m/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL — only used when no uploaded image is set.', max_length=500)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='catalog.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
