# Generated by Django 6.0.7 on 2026-09-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_seed_servicestep_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAfterCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Facial After-Care Tips', help_text="Header shown above the tips list, e.g. 'Facial After-Care Tips' or 'After-Care Tips'.", max_length=140)),
                ('tips', models.TextField(blank=True, help_text='Single box: Enter each after-care tip on a new line. They will be split and displayed as a bulleted UL list.')),
                ('service', models.OneToOneField(help_text='The service this after-care section belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='aftercare', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Service After-Care',
                'verbose_name_plural': 'Service After-Care Sections',
            },
        ),
    ]
