# Generated by Django 6.0.7 on 2026-07-28 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('address_label', models.CharField(max_length=60)),
                ('address_text', models.TextField()),
                ('address_pincode', models.CharField(blank=True, max_length=10)),
                ('address_lat', models.FloatField(blank=True, null=True)),
                ('address_lng', models.FloatField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('booking_type', models.CharField(choices=[('regular', 'Regular'), ('urgent', 'Urgent')], default='regular', max_length=10)),
                ('time_slot', models.CharField(blank=True, choices=[('morning', 'Morning (8 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 4 PM)'), ('evening', 'Evening (4 PM – 8 PM)')], max_length=10)),
                ('exact_time', models.TimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_at_home', 'Pay At Home')], max_length=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=140)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_snapshot', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('service_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='catalog.servicevariant')),
            ],
        ),
    ]
