# Generated by Django 6.0.7 on 2026-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='job_verification/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Pending'), ('on_the_way', 'On The Way'), ('in_progress', 'Job Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=12),
        ),
    ]
