# Generated by Django 6.0.7 on 2026-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_otp_generated_at_booking_otp_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='included_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
