# Generated by Django 6.0.7 on 2026-08-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingitem_included_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
