# Generated by Django 6.0.7 on 2026-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='otp_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
