# Generated by Django 6.0.7 on 2026-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_booking_verification_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
