# Generated by Django 6.0.7 on 2026-08-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_review_beautician_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='face_confidence_score',
            field=models.FloatField(blank=True, help_text='ML face match confidence score percentage (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='face_match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('mismatch', 'Mismatch'), ('no_face_detected', 'No Face Detected')], default='pending', max_length=20),
        ),
    ]
