# Generated by Django 6.0.7 on 2026-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_payment_status_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='beautician_rush_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rush allowance paid to beautician if starting within 30 min buffer (e.g. ₹50)', max_digits=7),
        ),
        migrations.AddField(
            model_name='booking',
            name='urgent_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra priority dispatch fee charged for urgent booking (e.g. ₹99)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='ntype',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('beautician_assigned', 'Beautician Assigned'), ('booking_rescheduled', 'Booking Rescheduled'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('on_the_way', 'Beautician On The Way'), ('job_started', 'Service Started'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
